/* tslint:disable */
/* eslint-disable */
/**
 * Deep3 Labs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHodlC1Response
 */
export interface GetHodlC1Response {
    /**
     * 
     * @type {number}
     * @memberof GetHodlC1Response
     */
    code: number;
    /**
     * 
     * @type {number}
     * @memberof GetHodlC1Response
     */
    result?: number;
}

/**
 * Check if a given object implements the GetHodlC1Response interface.
 */
export function instanceOfGetHodlC1Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function GetHodlC1ResponseFromJSON(json: any): GetHodlC1Response {
    return GetHodlC1ResponseFromJSONTyped(json, false);
}

export function GetHodlC1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHodlC1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function GetHodlC1ResponseToJSON(value?: GetHodlC1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'result': value.result,
    };
}

