/* tslint:disable */
/* eslint-disable */
/**
 * Deep3 Labs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPredictionResult
 */
export interface GetPredictionResult {
    /**
     * 
     * @type {number}
     * @memberof GetPredictionResult
     */
    code: number;
    /**
     * 
     * @type {number}
     * @memberof GetPredictionResult
     */
    result?: number;
}

/**
 * Check if a given object implements the GetPredictionResult interface.
 */
export function instanceOfGetPredictionResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function GetPredictionResultFromJSON(json: any): GetPredictionResult {
    return GetPredictionResultFromJSONTyped(json, false);
}

export function GetPredictionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPredictionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function GetPredictionResultToJSON(value?: GetPredictionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'result': value.result,
    };
}

