/* tslint:disable */
/* eslint-disable */
/**
 * Deep3 Labs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HodlC1XTokensRequestAddressesInner } from './HodlC1XTokensRequestAddressesInner';
import {
    HodlC1XTokensRequestAddressesInnerFromJSON,
    HodlC1XTokensRequestAddressesInnerFromJSONTyped,
    HodlC1XTokensRequestAddressesInnerToJSON,
} from './HodlC1XTokensRequestAddressesInner';

/**
 * 
 * @export
 * @interface HodlC1XTokensRequest
 */
export interface HodlC1XTokensRequest {
    /**
     * 
     * @type {Array<HodlC1XTokensRequestAddressesInner>}
     * @memberof HodlC1XTokensRequest
     */
    addresses?: Array<HodlC1XTokensRequestAddressesInner>;
}

/**
 * Check if a given object implements the HodlC1XTokensRequest interface.
 */
export function instanceOfHodlC1XTokensRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HodlC1XTokensRequestFromJSON(json: any): HodlC1XTokensRequest {
    return HodlC1XTokensRequestFromJSONTyped(json, false);
}

export function HodlC1XTokensRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HodlC1XTokensRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addresses': !exists(json, 'addresses') ? undefined : ((json['addresses'] as Array<any>).map(HodlC1XTokensRequestAddressesInnerFromJSON)),
    };
}

export function HodlC1XTokensRequestToJSON(value?: HodlC1XTokensRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addresses': value.addresses === undefined ? undefined : ((value.addresses as Array<any>).map(HodlC1XTokensRequestAddressesInnerToJSON)),
    };
}

