/* tslint:disable */
/* eslint-disable */
/**
 * Deep3 Labs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsResponse
 */
export interface ModelsResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsResponse
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ModelsResponse
     */
    chains: Array<number>;
}

/**
 * Check if a given object implements the ModelsResponse interface.
 */
export function instanceOfModelsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "chains" in value;

    return isInstance;
}

export function ModelsResponseFromJSON(json: any): ModelsResponse {
    return ModelsResponseFromJSONTyped(json, false);
}

export function ModelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'chains': json['chains'],
    };
}

export function ModelsResponseToJSON(value?: ModelsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'chains': value.chains,
    };
}

