/* tslint:disable */
/* eslint-disable */
/**
 * Deep3 Labs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostHodlC1XTokenRequestMappingsInner } from './PostHodlC1XTokenRequestMappingsInner';
import {
    PostHodlC1XTokenRequestMappingsInnerFromJSON,
    PostHodlC1XTokenRequestMappingsInnerFromJSONTyped,
    PostHodlC1XTokenRequestMappingsInnerToJSON,
} from './PostHodlC1XTokenRequestMappingsInner';

/**
 * 
 * @export
 * @interface PostHodlC1XTokenRequest
 */
export interface PostHodlC1XTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof PostHodlC1XTokenRequest
     */
    address: string;
    /**
     * 
     * @type {Array<PostHodlC1XTokenRequestMappingsInner>}
     * @memberof PostHodlC1XTokenRequest
     */
    mappings?: Array<PostHodlC1XTokenRequestMappingsInner>;
}

/**
 * Check if a given object implements the PostHodlC1XTokenRequest interface.
 */
export function instanceOfPostHodlC1XTokenRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function PostHodlC1XTokenRequestFromJSON(json: any): PostHodlC1XTokenRequest {
    return PostHodlC1XTokenRequestFromJSONTyped(json, false);
}

export function PostHodlC1XTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostHodlC1XTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'mappings': !exists(json, 'mappings') ? undefined : ((json['mappings'] as Array<any>).map(PostHodlC1XTokenRequestMappingsInnerFromJSON)),
    };
}

export function PostHodlC1XTokenRequestToJSON(value?: PostHodlC1XTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'mappings': value.mappings === undefined ? undefined : ((value.mappings as Array<any>).map(PostHodlC1XTokenRequestMappingsInnerToJSON)),
    };
}

