/* tslint:disable */
/* eslint-disable */
/**
 * Deep3 Labs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostHodlC1XTokenRequestMappingsInner
 */
export interface PostHodlC1XTokenRequestMappingsInner {
    /**
     * 
     * @type {number}
     * @memberof PostHodlC1XTokenRequestMappingsInner
     */
    chainId: number;
    /**
     * 
     * @type {string}
     * @memberof PostHodlC1XTokenRequestMappingsInner
     */
    address: string;
}

/**
 * Check if a given object implements the PostHodlC1XTokenRequestMappingsInner interface.
 */
export function instanceOfPostHodlC1XTokenRequestMappingsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chainId" in value;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function PostHodlC1XTokenRequestMappingsInnerFromJSON(json: any): PostHodlC1XTokenRequestMappingsInner {
    return PostHodlC1XTokenRequestMappingsInnerFromJSONTyped(json, false);
}

export function PostHodlC1XTokenRequestMappingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostHodlC1XTokenRequestMappingsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chainId': json['chainId'],
        'address': json['address'],
    };
}

export function PostHodlC1XTokenRequestMappingsInnerToJSON(value?: PostHodlC1XTokenRequestMappingsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chainId': value.chainId,
        'address': value.address,
    };
}

