/* tslint:disable */
/* eslint-disable */
/**
 * Deep3 Labs API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostHodlC1XTokensRequestAddressesInner } from './PostHodlC1XTokensRequestAddressesInner';
import {
    PostHodlC1XTokensRequestAddressesInnerFromJSON,
    PostHodlC1XTokensRequestAddressesInnerFromJSONTyped,
    PostHodlC1XTokensRequestAddressesInnerToJSON,
} from './PostHodlC1XTokensRequestAddressesInner';

/**
 * 
 * @export
 * @interface PostHodlC1XTokensRequest
 */
export interface PostHodlC1XTokensRequest {
    /**
     * 
     * @type {Array<PostHodlC1XTokensRequestAddressesInner>}
     * @memberof PostHodlC1XTokensRequest
     */
    addresses?: Array<PostHodlC1XTokensRequestAddressesInner>;
}

/**
 * Check if a given object implements the PostHodlC1XTokensRequest interface.
 */
export function instanceOfPostHodlC1XTokensRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostHodlC1XTokensRequestFromJSON(json: any): PostHodlC1XTokensRequest {
    return PostHodlC1XTokensRequestFromJSONTyped(json, false);
}

export function PostHodlC1XTokensRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostHodlC1XTokensRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addresses': !exists(json, 'addresses') ? undefined : ((json['addresses'] as Array<any>).map(PostHodlC1XTokensRequestAddressesInnerFromJSON)),
    };
}

export function PostHodlC1XTokensRequestToJSON(value?: PostHodlC1XTokensRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addresses': value.addresses === undefined ? undefined : ((value.addresses as Array<any>).map(PostHodlC1XTokensRequestAddressesInnerToJSON)),
    };
}

